comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

codecov:
  token: 8cd3b4cb-4ba6-4f09-b302-61a856b82970
language: R

sudo: false

cache: packages

after_success:

- Rscript -e 'covr::codecov()'
