library(digest)
library(stringr)
library(dplyr)
library(pryr)
library(ggplot2)
library(patchwork)
library(SnowballC)

source("../../R/data-analyzer.R")
source("../../R/data-cleaner.R")
source("../../R/data-sampler.R")
source("../../R/text-file-processor.R")
source("../../R/token-generator.R")
source("../../R/tp-generator.R")
source("../../R/model/model.R")
source("../../R/model/model-evaluator.R")
source("../../R/model/model-generator.R")
source("../../R/model/model-predictor.R")
